"""
03_render_replica_images.py
----------------------------
Renders images from Replica 3D scenes using Habitat-Sim for use as visual conditioning
in the Gen-RIR-Diffusion model. Two image types are supported:

  target2source  — Per (receiver, source) pair: camera placed at receiver position,
                   facing exactly toward source. File: tgt{r}_src{s}.png
                   Captures the acoustic path geometry from the listener's perspective.

  room_panorama  — Per scene: 360° equirectangular image from the centroid of all
                   navigable positions. File: {scene_name}_pano_depth.png (or _pano_rgb.png)
                   Captures global room geometry for all pairs in the scene.

Both types support depth and RGB sensor output. Default is depth.
Output folders are named: {view}_{type}/  (e.g. target2source_depth/)

REQUIREMENTS:
  conda activate habitat
  export MAGNUM_LOG=quiet HABITAT_SIM_LOG=quiet

  habitat-sim v0.3.3 must be installed in the active conda environment.
  Run: conda activate habitat

COORDINATE SYSTEM:
  points.txt uses Z-up coordinates (X, Y = horizontal; Z = constant floor height).
  Habitat-Sim uses Y-up. Transform applied: habitat_pos = (x_pts, z_pts, y_pts).
  Heading angles 0/90/180/270 map to facing directions in Habitat's coordinate frame.
  *** Verify visually on a test run before processing all scenes. ***

Usage:
    conda activate habitat
    python3 data/data_preparation/03_render_replica_images.py --scenes office_1 --max-pairs 10
    python3 data/data_preparation/03_render_replica_images.py  # full render, all scenes
"""

import argparse
import csv
import json
import math
import pickle
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np

try:
    import habitat_sim
    import habitat_sim.utils.common as utils
except ImportError:
    print("ERROR: habitat_sim not found. Activate the correct conda environment:")
    print("  conda activate habitat")
    sys.exit(1)

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow not found. Install with: pip install Pillow")
    sys.exit(1)

# ─── Default paths ────────────────────────────────────────────────────────────

DEFAULT_REPLICA_ROOT   = "/dsi/gannot-lab/gannot-lab1/datasets/Replica"
DEFAULT_METADATA_ROOT  = "/dsi/gannot-lab/gannot-lab1/datasets/SoundSpaces/metadata/replica"
DEFAULT_OUTPUT_ROOT    = "/dsi/gannot-lab/gannot-lab1/datasets/Replica_rendered"
DEFAULT_MAPPING_CSV    = Path(__file__).resolve().parents[1] / "soundspaces_replica_mapping.csv"

SUPPORTED_VIEWS = ["target2source", "room_panorama"]
SUPPORTED_TYPES = ["depth", "rgb"]
ANGLES = [0, 90, 180, 270]

# Height above the floor at which the camera is placed (meters).
# Points.txt Z values are at floor level (~0.009 m); SoundSpaces places receivers
# at 1.5 m eye height, so we add this offset when converting to Habitat coords.
EYE_HEIGHT = 1.5


# ─── Points / graph loading ───────────────────────────────────────────────────

def parse_points(points_file: Path) -> dict:
    """Parse points.txt → {idx: (x, y, z)} in Z-up coordinates."""
    positions = {}
    with open(points_file) as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) == 4:
                idx = int(parts[0])
                positions[idx] = (float(parts[1]), float(parts[2]), float(parts[3]))
    return positions


def load_mapping_csv(csv_path: Path, scene_name: str) -> list[dict]:
    """
    Load rows from the mapping CSV (generated by 02_preprocess_soundspaces.py)
    for a specific scene. Skips comment lines starting with '#'.

    Returns a list of dicts with keys: receiver_idx, source_idx,
    receiver_x/y/z, source_x/y/z (as floats).
    """
    rows = []
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(
            (line for line in f if not line.startswith("#"))
        )
        for row in reader:
            if row["scene"] == scene_name:
                rows.append({
                    "receiver_idx": int(row["receiver_idx"]),
                    "source_idx":   int(row["source_idx"]),
                    "receiver_pos": (float(row["receiver_x"]), float(row["receiver_y"]), float(row["receiver_z"])),
                    "source_pos":   (float(row["source_x"]),   float(row["source_y"]),   float(row["source_z"])),
                })
    return rows


def pts_to_habitat(pos: tuple) -> np.ndarray:
    """
    Convert a position from points.txt Z-up coords to Habitat-Sim Y-up coords,
    raising the camera to eye height above the floor.

    points.txt: (x, y, z) where x,y = floor plane, z = floor height (constant ~0.009 m)
    habitat:    (x, y, z) where y = up
    Transform: habitat = (pts_x, pts_z + EYE_HEIGHT, pts_y)
    *** Verify this transform is correct on a test run. ***
    """
    return np.array([pos[0], pos[2] + EYE_HEIGHT, pos[1]], dtype=np.float32)


def facing_quaternion(receiver_pos: tuple, source_pos: tuple):
    """
    Compute a habitat_sim rotation quaternion for the agent at receiver_pos
    to face exactly toward source_pos, in the horizontal plane (Y-up).

    Both positions are in points.txt Z-up coords and converted internally.
    """
    r = pts_to_habitat(receiver_pos)
    s = pts_to_habitat(source_pos)
    direction = s - r
    direction[1] = 0  # project to horizontal plane (ignore height difference)
    norm = np.linalg.norm(direction)
    if norm < 1e-6:
        return utils.quat_from_angle_axis(0.0, np.array([0, 1, 0]))
    direction /= norm
    # Habitat default forward = -Z. After rotation θ around Y-up,
    # forward = [-sin(θ), 0, -cos(θ)]. To face direction [dx, 0, dz]:
    #   -sin(θ) = dx  →  sin(θ) = -dx
    #   -cos(θ) = dz  →  cos(θ) = -dz
    #   θ = atan2(-dx, -dz)
    angle = math.atan2(-float(direction[0]), -float(direction[2]))
    return utils.quat_from_angle_axis(angle, np.array([0, 1, 0]))


def heading_quaternion(heading_deg: float):
    """Quaternion for a given heading angle (degrees), rotating around Y-up axis."""
    return utils.quat_from_angle_axis(math.radians(heading_deg), np.array([0, 1, 0]))


# ─── Habitat-Sim setup ────────────────────────────────────────────────────────

def build_simulator(mesh_path: Path, image_size: int, views: list, sensor_types: list):
    """
    Create and return a Habitat-Sim simulator with the requested sensors attached.

    Sensors added:
      - "depth_pinhole"  if "target2source" in views and "depth" in sensor_types
      - "rgb_pinhole"    if "target2source" in views and "rgb"   in sensor_types
      - "depth_equirect" if "room_panorama"  in views and "depth" in sensor_types
      - "rgb_equirect"   if "room_panorama"  in views and "rgb"   in sensor_types
    """
    backend_cfg = habitat_sim.SimulatorConfiguration()
    backend_cfg.scene_id = str(mesh_path)
    backend_cfg.enable_physics = False

    sensor_specs = []

    # Pinhole sensors (target2source)
    if "target2source" in views:
        if "depth" in sensor_types:
            s = habitat_sim.CameraSensorSpec()
            s.uuid = "depth_pinhole"
            s.sensor_type = habitat_sim.SensorType.DEPTH
            s.sensor_subtype = habitat_sim.SensorSubType.PINHOLE
            s.resolution = [image_size, image_size]
            sensor_specs.append(s)
        if "rgb" in sensor_types:
            s = habitat_sim.CameraSensorSpec()
            s.uuid = "rgb_pinhole"
            s.sensor_type = habitat_sim.SensorType.COLOR
            s.sensor_subtype = habitat_sim.SensorSubType.PINHOLE
            s.resolution = [image_size, image_size]
            sensor_specs.append(s)

    # Equirectangular sensors (room_panorama)
    if "room_panorama" in views:
        pano_h, pano_w = image_size, image_size * 2  # 2:1 for equirectangular
        if "depth" in sensor_types:
            s = habitat_sim.EquirectangularSensorSpec()
            s.uuid = "depth_equirect"
            s.sensor_type = habitat_sim.SensorType.DEPTH
            s.resolution = [pano_h, pano_w]
            sensor_specs.append(s)
        if "rgb" in sensor_types:
            s = habitat_sim.EquirectangularSensorSpec()
            s.uuid = "rgb_equirect"
            s.sensor_type = habitat_sim.SensorType.COLOR
            s.resolution = [pano_h, pano_w]
            sensor_specs.append(s)

    agent_cfg = habitat_sim.agent.AgentConfiguration()
    agent_cfg.sensor_specifications = sensor_specs

    cfg = habitat_sim.Configuration(backend_cfg, [agent_cfg])
    return habitat_sim.Simulator(cfg)


def set_agent_state(sim, position_habitat: np.ndarray, rotation):
    """Place the agent at the given Y-up position with the given rotation."""
    agent = sim.get_agent(0)
    state = habitat_sim.AgentState()
    state.position = position_habitat
    state.rotation = rotation
    agent.set_state(state)


def get_observations(sim) -> dict:
    return sim.get_sensor_observations()


# ─── Image saving ─────────────────────────────────────────────────────────────

def save_depth(arr: np.ndarray, path: Path):
    """
    Save a float32 depth array (meters) as a 16-bit PNG.
    Values are clipped to [0, 65.535] m and stored as uint16 (1 unit = 1 mm).
    """
    depth_mm = np.clip(arr * 1000, 0, 65535).astype(np.uint16)
    Image.fromarray(depth_mm, mode="I;16").save(path)


def save_rgb(arr: np.ndarray, path: Path):
    """Save an RGBA or RGB uint8 array as PNG."""
    if arr.shape[2] == 4:
        arr = arr[:, :, :3]
    Image.fromarray(arr.astype(np.uint8), mode="RGB").save(path)


def save_observation(obs: dict, uuid: str, sensor_type: str, path: Path):
    """Save a single observation to disk based on sensor type."""
    data = obs[uuid]
    if sensor_type == "depth":
        save_depth(data, path)
    else:
        save_rgb(data, path)


# ─── Manifest helpers ─────────────────────────────────────────────────────────

def load_manifest(manifest_path: Path) -> dict:
    if manifest_path.exists():
        with open(manifest_path) as f:
            return json.load(f)
    return {}


def save_manifest(manifest_path: Path, data: dict):
    with open(manifest_path, "w") as f:
        json.dump(data, f, indent=2)


def count_existing_images(scene_dir: Path, prefix: str = "tgt") -> int:
    """Count existing .png files with the given prefix in a directory."""
    return sum(1 for f in scene_dir.glob(f"{prefix}*.png"))


# ─── Main render functions ────────────────────────────────────────────────────

def save_metadata_txt(path: Path, scene_name: str, receiver_idx: int, source_idx: int,
                      rx_pos: tuple, sx_pos: tuple, habitat_pos: np.ndarray,
                      sensor_types: list, image_size: int, mesh_name: str):
    """Write a human-readable metadata .txt alongside a rendered image."""
    r_hab = pts_to_habitat(rx_pos)
    s_hab = pts_to_habitat(sx_pos)
    d = s_hab - r_hab
    d[1] = 0
    dist_h = float(np.linalg.norm(d))
    if dist_h > 1e-6:
        d_norm = d / dist_h
    else:
        d_norm = np.zeros(3)
    angle = math.atan2(-float(d_norm[0]), -float(d_norm[2]))

    lines = [
        f"scene:                  {scene_name}",
        f"receiver_idx:           {receiver_idx}",
        f"source_idx:             {source_idx}",
        f"receiver_pts (Z-up):    x={rx_pos[0]:.6f}  y={rx_pos[1]:.6f}  z={rx_pos[2]:.6f}",
        f"source_pts   (Z-up):    x={sx_pos[0]:.6f}  y={sx_pos[1]:.6f}  z={sx_pos[2]:.6f}",
        f"receiver_habitat (Y-up): x={r_hab[0]:.6f}  y={r_hab[1]:.6f}  z={r_hab[2]:.6f}",
        f"source_habitat   (Y-up): x={s_hab[0]:.6f}  y={s_hab[1]:.6f}  z={s_hab[2]:.6f}",
        f"horizontal_distance_m:  {dist_h:.4f}",
        f"camera_yaw_rad:         {angle:.6f}  ({math.degrees(angle):.2f} deg around Y-up)",
        f"camera_forward_dir:     x={-math.sin(angle):.4f}  y=0  z={-math.cos(angle):.4f}",
        f"eye_height_m:           {EYE_HEIGHT}",
        f"mesh:                   {mesh_name}",
        f"image_size:             {image_size}x{image_size}",
        f"sensor_types:           {', '.join(sensor_types)}",
        f"rendered_at:            {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
    ]
    path.write_text("\n".join(lines) + "\n")


def render_target2source(
    sim,
    scene_name: str,
    mapping_rows: list[dict],
    sensor_types: list,
    output_dirs: dict,
    max_pairs: Optional[int],
    skip_existing: bool,
    save_metadata: bool = False,
    image_size: int = 256,
    mesh_name: str = "mesh.ply",
) -> dict:
    """
    Render one image per (receiver, source) pair from the mapping CSV:
    camera placed at receiver position, facing exactly toward source.

    mapping_rows: list of dicts from load_mapping_csv() for this scene.
    Returns stats dict.
    """
    n_rendered = 0
    n_skipped = 0

    rows = mapping_rows[:max_pairs] if max_pairs is not None else mapping_rows

    for row in rows:
        receiver_idx = row["receiver_idx"]
        source_idx   = row["source_idx"]
        rx_pos       = row["receiver_pos"]
        sx_pos       = row["source_pos"]

        rotation    = facing_quaternion(rx_pos, sx_pos)
        habitat_pos = pts_to_habitat(rx_pos)

        rendered_any = False
        for sensor_type in sensor_types:
            out_dir = output_dirs[f"target2source_{sensor_type}"] / scene_name
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path = out_dir / f"tgt{receiver_idx}_src{source_idx}.png"

            if skip_existing and out_path.exists():
                n_skipped += 1
                continue

            set_agent_state(sim, habitat_pos, rotation)
            obs = get_observations(sim)
            save_observation(obs, f"{sensor_type}_pinhole", sensor_type, out_path)

            if save_metadata:
                txt_path = out_path.with_suffix(".txt")
                save_metadata_txt(txt_path, scene_name, receiver_idx, source_idx,
                                  rx_pos, sx_pos, habitat_pos,
                                  sensor_types, image_size, mesh_name)
            rendered_any = True

        if rendered_any:
            n_rendered += 1

    return {"n_pairs_rendered": n_rendered, "n_pairs_skipped": n_skipped}


def render_room_panorama(
    sim,
    scene_name: str,
    positions: dict,
    graph_nodes: list,
    sensor_types: list,
    output_dirs: dict,
    skip_existing: bool,
) -> dict:
    """
    Render one equirectangular panorama per scene from the centroid of all graph nodes.
    Returns stats dict.
    """
    # Compute centroid of graph nodes
    coords = [positions[n] for n in graph_nodes]
    cx = sum(c[0] for c in coords) / len(coords)
    cy = sum(c[1] for c in coords) / len(coords)
    cz = sum(c[2] for c in coords) / len(coords)
    centroid = (cx, cy, cz)
    habitat_centroid = pts_to_habitat(centroid)

    rendered = []
    for sensor_type in sensor_types:
        out_dir = output_dirs[f"room_panorama_{sensor_type}"]
        out_dir.mkdir(parents=True, exist_ok=True)
        suffix = "depth" if sensor_type == "depth" else "rgb"
        out_path = out_dir / f"{scene_name}_pano_{suffix}.png"

        if skip_existing and out_path.exists():
            continue

        # Facing default direction (heading=0) — panorama covers all directions anyway
        rotation = heading_quaternion(0.0)
        set_agent_state(sim, habitat_centroid, rotation)
        obs = get_observations(sim)

        uuid = f"{sensor_type}_equirect"
        save_observation(obs, uuid, sensor_type, out_path)
        rendered.append(sensor_type)

    return {"panoramas_rendered": rendered, "centroid": list(centroid)}


# ─── Per-scene entry point ────────────────────────────────────────────────────

def process_scene(
    scene_name: str,
    replica_root: Path,
    metadata_root: Path,
    mapping_csv: Path,
    output_dirs: dict,
    views: list,
    sensor_types: list,
    image_size: int,
    max_pairs: Optional[int],
    skip_existing: bool,
    save_metadata: bool = False,
):
    # Use mesh.ply (vertex colors) for RGB; mesh_semantic.ply for depth-only.
    # mesh.ply gives correct colors; mesh_semantic.ply gives semantic label colors.
    if "rgb" in sensor_types:
        mesh_path = replica_root / scene_name / "mesh.ply"
        mesh_name = "mesh.ply"
    else:
        mesh_path = replica_root / scene_name / "habitat" / "mesh_semantic.ply"
        mesh_name = "habitat/mesh_semantic.ply"

    if not mesh_path.exists():
        print(f"  WARNING: mesh not found: {mesh_path}")
        return

    # Load graph nodes for room_panorama centroid (positions from mapping CSV for target2source)
    with open(metadata_root / scene_name / "graph.pkl", "rb") as f:
        graph = pickle.load(f)
    graph_nodes = sorted(graph.nodes())
    positions = parse_points(metadata_root / scene_name / "points.txt")

    # Load mapping CSV rows for this scene (used by target2source)
    mapping_rows = []
    if "target2source" in views:
        if not mapping_csv.exists():
            print(f"  ERROR: mapping CSV not found: {mapping_csv}")
            print(f"  Run 02_preprocess_soundspaces.py first.")
            return
        mapping_rows = load_mapping_csv(mapping_csv, scene_name)
        if not mapping_rows:
            print(f"  WARNING: no rows found for scene '{scene_name}' in mapping CSV — skipping")
            return

    print(
        f"  Loading scene '{scene_name}' "
        f"({len(graph_nodes)} graph nodes"
        + (f", {len(mapping_rows)} pairs from CSV" if mapping_rows else "")
        + ")...",
        flush=True,
    )
    sim = build_simulator(mesh_path, image_size, views, sensor_types)

    stats = {
        "scene": scene_name,
        "rendered_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "views": views,
        "sensor_types": sensor_types,
        "image_size": image_size,
        "n_graph_nodes": len(graph_nodes),
        "n_mapping_pairs": len(mapping_rows),
        "mesh": mesh_name,
    }

    if "target2source" in views:
        t2s_stats = render_target2source(
            sim, scene_name, mapping_rows,
            sensor_types, output_dirs, max_pairs, skip_existing,
            save_metadata=save_metadata, image_size=image_size, mesh_name=mesh_name,
        )
        stats["target2source"] = t2s_stats
        print(
            f"    target2source: {t2s_stats['n_pairs_rendered']} rendered"
            + (f", {t2s_stats['n_pairs_skipped']} skipped" if t2s_stats["n_pairs_skipped"] else "")
        )

    if "room_panorama" in views:
        pano_stats = render_room_panorama(
            sim, scene_name, positions, graph_nodes,
            sensor_types, output_dirs, skip_existing,
        )
        stats["room_panorama"] = pano_stats
        print(f"    room_panorama: centroid at {[round(c,3) for c in pano_stats['centroid']]}")

    sim.close()

    # Write manifest inside the first target2source dir (or first output dir available)
    manifest_parent = next(iter(output_dirs.values())) / scene_name
    manifest_parent.mkdir(parents=True, exist_ok=True)
    save_manifest(manifest_parent / "manifest.json", stats)


# ─── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Render Replica scene images for Gen-RIR-Diffusion model conditioning."
    )
    parser.add_argument("--replica-root",   type=Path, default=DEFAULT_REPLICA_ROOT)
    parser.add_argument("--metadata-root",  type=Path, default=DEFAULT_METADATA_ROOT)
    parser.add_argument("--output-root",    type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--mapping-csv",    type=Path, default=DEFAULT_MAPPING_CSV,
                        help="Path to soundspaces_replica_mapping.csv (from 02_preprocess_soundspaces.py)")
    parser.add_argument(
        "--views",
        type=str,
        default="target2source",
        help=f"Comma-separated views to render: {SUPPORTED_VIEWS} (default: target2source)",
    )
    parser.add_argument(
        "--types",
        type=str,
        default="rgb",
        help=f"Comma-separated image types: {SUPPORTED_TYPES} (default: rgb)",
    )
    parser.add_argument("--save-metadata", action="store_true",
                        help="Save a .txt file alongside each image with camera/position details")
    parser.add_argument("--image-size",    type=int, default=256,
                        help="Pixel size (WxH for pinhole, H for panorama H×2H)")
    parser.add_argument("--scenes",        type=str, default=None,
                        help="Comma-separated scene names (default: all)")
    parser.add_argument("--max-pairs",     type=int, default=None,
                        help="Max (target,source) pairs per scene — for test runs")
    parser.add_argument("--no-skip",       action="store_true",
                        help="Re-render even if output file already exists")
    args = parser.parse_args()

    views = [v.strip() for v in args.views.split(",")]
    sensor_types = [t.strip() for t in args.types.split(",")]

    for v in views:
        if v not in SUPPORTED_VIEWS:
            print(f"ERROR: unknown view '{v}'. Choose from: {SUPPORTED_VIEWS}")
            sys.exit(1)
    for t in sensor_types:
        if t not in SUPPORTED_TYPES:
            print(f"ERROR: unknown type '{t}'. Choose from: {SUPPORTED_TYPES}")
            sys.exit(1)

    # Build output directory map: "target2source_depth" → Path(...)
    output_dirs = {}
    for v in views:
        for t in sensor_types:
            key = f"{v}_{t}"
            output_dirs[key] = args.output_root / key

    # Discover scenes
    if args.scenes:
        scenes = [s.strip() for s in args.scenes.split(",")]
    else:
        scenes = sorted(d.name for d in args.metadata_root.iterdir() if d.is_dir())

    print(f"\nRendering {len(scenes)} scene(s)  |  views: {views}  |  types: {sensor_types}")
    print(f"Output root: {args.output_root}\n")

    for scene in scenes:
        print(f"Scene: {scene}")
        process_scene(
            scene_name=scene,
            replica_root=args.replica_root,
            metadata_root=args.metadata_root,
            mapping_csv=args.mapping_csv,
            output_dirs=output_dirs,
            views=views,
            sensor_types=sensor_types,
            image_size=args.image_size,
            max_pairs=args.max_pairs,
            skip_existing=not args.no_skip,
            save_metadata=args.save_metadata,
        )
        print()

    print("Done.")


if __name__ == "__main__":
    main()
